// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqytxnzogkaufdrsmsfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxeXR4bnpvZ2thdWZkcnNtc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODcxMzEsImV4cCI6MjA3MTM2MzEzMX0.qNUgQBs3ziBVMiht9PVay7nRmdgFrwY763Qdf64Wn4I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});